export const ATTACK_DEFINITIONS = {
  slash: {
    id: "slash",
    range: 75,
    damage: 5,
    intervalMs: 1000,
    durationMs: 260,
    aimSmoothingSeconds: 0.08,
  },
  arrow: {
    id: "arrow",
    range: 1000,
    manualRange: 1000,
    speed: 600,
    damage: 5,
    count: 2,
    spreadRadians: Math.PI / 30,
    piercing: true,
  },
  fireball: {
    id: "fireball",
    range: 250,
    manualRange: 1000,
    speed: 380,
    damage: 3,
    count: 2,
    spreadRadians: Math.PI / 30,
    splashRadius: 100,
    splashDamage: 1,
    piercing: false,
  },
  roots: {
    id: "roots",
    range: 250,
    manualRange: 1000,
    speed: 380,
    damage: 3,
    count: 1,
    spreadRadians: Math.PI / 30,
    bounces: 3,
    bounceRadius: 250,
    piercing: false,
  },
} as const;
